import Head from 'next/head'
import SideBar from '../components/Sidebar'

export default function Home() {
  return (
    <div className="max-h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SideBar />
    </div>
  )
}
